# 🌟 Exercise 1 : Array Creation and Manipulation


In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 🌟 Exercise 2 : Type Conversion and Array Operations

In [10]:
array_int = np.array([3.14, 2.17, 0, 1, 2])
array_int.astype(int)

array([3, 2, 0, 1, 2])

# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays


In [7]:
array_3x3 = np.arange(1, 10).reshape(3, 3)
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers


In [ ]:
array_2d = np.random.rand(4, 5)
array_2d

array([[0.6098364 , 0.5965697 , 0.93767511, 0.97979748, 0.45152012],
       [0.18900573, 0.2071338 , 0.00469925, 0.74563664, 0.12941565],
       [0.83116645, 0.28607149, 0.22296068, 0.9410999 , 0.15729604],
       [0.67797814, 0.1061953 , 0.84265005, 0.34458672, 0.03517667]])

# 🌟 Exercise 5 : Indexing Arrays


In [13]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1]


array([20, 21, 22, 23, 24])

# 🌟 Exercise 6 : Reversing elements


In [15]:
array1 = np.arange(10)
array1_reversed = array1[::-1]
print("the array : ", array1)
print("the reversed array : ", array1_reversed)

the array :  [0 1 2 3 4 5 6 7 8 9]
the reversed array :  [9 8 7 6 5 4 3 2 1 0]


# 🌟 Exercise 7 : Identity Matrix


In [16]:
identify_matrix = np.eye(4)
identify_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 🌟 Exercise 8 : Simple Aggregate Funcs


In [30]:
array2 =np.array([11, 1, 0.33, 0.29, 79, 7, 3 , 9, 45, 52])
print("The sum : " , array2.sum())
print("The average : " ,array2.mean())

The sum :  207.62
The average :  20.762


# 🌟 Exercise 9 : Create Array and Change its Structure


In [33]:
arr1 = np.random.randint(0, 100, 20)
arr2 = arr1.reshape(4, 5)
print("The reshaped of the giving array is : ", arr2)

The reshaped of the giving array is :  [[49  0 26  8 26]
 [93 61 32 26 32]
 [51 45 67  8 89]
 [42 58 21 64 23]]


# 🌟 Exercise 10 : Conditional Selection of Values


In [34]:
array_4 = np.arange(10)
array_4[array_4 % 2 == 1]

array([1, 3, 5, 7, 9])